import './globals.css';

import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';

import { ApolloWrapper } from '@/libs/apollo/wrapper';
import { ThemeProvider } from '@/libs/themes/wrapper';

const font = Noto_Sans({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={font.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ApolloWrapper>{children}</ApolloWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
