import './globals.css';

import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';

import { ApolloWrapper } from '@/libs/apollo/wrapper';

const font = Noto_Sans({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  );
}
